import { useState, useContext, useEffect, useRef } from "react";
import { Link, useNavigate } from "react-router-dom";
import { AuthContext } from "../../context/AuthContext";
import api from "../../services/api";
import { motion } from "framer-motion";
import { toast } from "react-hot-toast";
import { User, Mail, Phone, Lock, Loader2, ArrowRight, HelpCircle, KeyRound, Eye, EyeOff, Sparkles, Github } from "lucide-react";

const Register = () => {
  const { register, isAuthenticated, loading } = useContext(AuthContext);
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [phone, setPhone] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  
  // OTP States
  const [otp, setOtp] = useState("");
  const [otpSent, setOtpSent] = useState(false);
  const [otpSending, setOtpSending] = useState(false);
  const [cooldown, setCooldown] = useState(0);
  const [isSubmitting, setIsSubmitting] = useState(false);
  
  const timerRef = useRef(null);
  const navigate = useNavigate();

  // Helper to generate a suggested secure password meeting registration rules
  const generateSuggestedPassword = () => {
    const uppercase = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    const lowercase = "abcdefghijklmnopqrstuvwxyz";
    const numbers = "0123456789";
    const special = "!@#$%^&*()";
    
    let chars = [];
    // Select 3 random characters from each character class
    for (let i = 0; i < 3; i++) {
      chars.push(uppercase[Math.floor(Math.random() * uppercase.length)]);
      chars.push(lowercase[Math.floor(Math.random() * lowercase.length)]);
      chars.push(numbers[Math.floor(Math.random() * numbers.length)]);
      chars.push(special[Math.floor(Math.random() * special.length)]);
    }
    
    // Shuffle the characters array for complexity
    for (let i = chars.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      const temp = chars[i];
      chars[i] = chars[j];
      chars[j] = temp;
    }
    
    const generated = chars.join("");
    setPassword(generated);
    setConfirmPassword(generated);
    setShowPassword(true); // Temporarily reveal password so user can save it
    toast.success("Generated a strong, secure password for you!");
  };

  // Simulated Social Auth Handler for Google, Microsoft, GitHub, and Mobile signup
  const handleSocialRegister = async (provider) => {
    setIsSubmitting(true);
    toast.loading(`Connecting to ${provider} authentication services...`, { id: "social-auth" });
    
    // Simulate OAuth / Mobile sign-up handshake
    setTimeout(async () => {
      try {
        const randomId = Math.floor(1000 + Math.random() * 9000);
        let mockName, mockEmail, mockPhone;

        if (provider === "Mobile") {
          mockName = "Mobile User";
          mockPhone = "9414407192";
          mockEmail = `phone_${mockPhone}_${randomId}@supportsphere.ai`;
        } else {
          mockName = `${provider} User`;
          mockEmail = `${provider.toLowerCase()}_user_${randomId}@supportsphere.ai`;
          mockPhone = "9414407192";
        }
        
        const result = await register(
          mockName,
          mockEmail,
          "", // password (auto-generated by backend if empty)
          mockPhone,
          "", // otp (bypassed by isOAuth flag)
          true // isOAuth = true
        );
        
        if (result.success) {
          toast.success(`Welcome to SupportSphere, ${result.user.name}!`, { id: "social-auth" });
          navigate("/dashboard", { replace: true });
        } else {
          toast.error(result.error || "Social authentication failed.", { id: "social-auth" });
        }
      } catch (error) {
        toast.error("Social identity sync failed.", { id: "social-auth" });
      } finally {
        setIsSubmitting(false);
      }
    }, 1200);
  };

  useEffect(() => {
    if (isAuthenticated) {
      navigate("/dashboard", { replace: true });
    }
  }, [isAuthenticated, navigate]);

  // Cooldown timer handler
  useEffect(() => {
    if (cooldown > 0) {
      timerRef.current = setTimeout(() => {
        setCooldown(cooldown - 1);
      }, 1000);
    }
    return () => {
      if (timerRef.current) clearTimeout(timerRef.current);
    };
  }, [cooldown]);

  // Handler to request OTP
  const handleSendOtp = async (e) => {
    e.preventDefault();

    if (!email) {
      toast.error("Please enter your email address first.");
      return;
    }

    // Email regex validation
    const emailRegex = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;
    if (!emailRegex.test(email)) {
      toast.error("Please enter a valid email address.");
      return;
    }

    setOtpSending(true);
    try {
      const response = await api.post("/auth/send-otp", { email });
      if (response.data.success) {
        setOtpSent(true);
        setCooldown(50);
        toast.success("Verification code sent! Check your server console terminal.");
      }
    } catch (error) {
      const message = error.response?.data?.message || "Failed to send verification code.";
      toast.error(message);
    } finally {
      setOtpSending(false);
    }
  };

  // Handler to submit complete registration
  const handleSubmit = async (e) => {
    e.preventDefault();

    // Client-side validations
    if (!name || !email || !password || !confirmPassword || !otp) {
      toast.error("Please fill in all required fields including the verification code.");
      return;
    }

    if (password.length < 8) {
      toast.error("Password must be at least 8 characters long.");
      return;
    }

    if (password !== confirmPassword) {
      toast.error("Passwords do not match.");
      return;
    }

    // Password complexity check
    const passwordRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*(),.?":{}|<>]).{8,}$/;
    if (!passwordRegex.test(password)) {
      toast.error("Password must contain uppercase, lowercase, numbers, and special characters.");
      return;
    }

    setIsSubmitting(true);
    const result = await register(name, email, password, phone, otp);
    setIsSubmitting(false);

    if (result.success) {
      toast.success(`Welcome to SupportSphere, ${result.user.name}!`);
      navigate("/dashboard", { replace: true });
    } else {
      toast.error(result.error);
    }
  };

  return (
    <div className="min-h-[calc(100vh-4rem-4rem)] flex items-center justify-center px-4 sm:px-6 lg:px-8 py-12 relative overflow-hidden bg-[#0F172A]">
      {/* Background Decorative Gradients */}
      <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-blue-600/10 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-purple-600/10 rounded-full blur-3xl pointer-events-none" />

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="w-full max-w-md z-10"
      >
        {/* Header Branding */}
        <div className="text-center mb-6">
          <div className="inline-flex h-12 w-12 rounded-2xl bg-gradient-to-tr from-[#2563EB] to-[#7C3AED] items-center justify-center text-white shadow-xl shadow-blue-500/20 mb-4">
            <HelpCircle className="h-6 w-6" />
          </div>
          <h2 className="text-3xl font-extrabold text-white tracking-tight">
            Create an Account
          </h2>
          <p className="mt-2 text-sm text-[#CBD5E1]">
            Join SupportSphere to start resolving complaints with AI
          </p>
        </div>

        {/* Card Form */}
        <div className="bg-[#1E293B]/40 backdrop-blur-xl border border-[#334155]/60 rounded-2xl p-8 shadow-2xl">
          <form className="space-y-4" onSubmit={handleSubmit}>
            
            {/* Name Field */}
            <div>
              <label className="block text-xs font-semibold text-[#CBD5E1] uppercase tracking-wider mb-1.5" htmlFor="name">
                Full Name *
              </label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-[#CBD5E1]/60">
                  <User className="h-4.5 w-4.5" />
                </div>
                <input
                  id="name"
                  type="text"
                  required
                  disabled={otpSent}
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  className="block w-full pl-10 pr-4 py-2.5 bg-[#0F172A]/60 border border-[#334155] rounded-xl text-white placeholder-[#CBD5E1]/40 focus:ring-2 focus:ring-[#2563EB] focus:border-transparent outline-none transition-all duration-200 text-sm disabled:opacity-50"
                  placeholder="John Doe"
                />
              </div>
            </div>

            {/* Email Field */}
            <div>
              <label className="block text-xs font-semibold text-[#CBD5E1] uppercase tracking-wider mb-1.5" htmlFor="email">
                Email Address *
              </label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-[#CBD5E1]/60">
                  <Mail className="h-4.5 w-4.5" />
                </div>
                <input
                  id="email"
                  type="email"
                  required
                  disabled={otpSent}
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  className="block w-full pl-10 pr-4 py-2.5 bg-[#0F172A]/60 border border-[#334155] rounded-xl text-white placeholder-[#CBD5E1]/40 focus:ring-2 focus:ring-[#2563EB] focus:border-transparent outline-none transition-all duration-200 text-sm disabled:opacity-50"
                  placeholder="john@organization.com"
                />
              </div>
            </div>

            {/* Phone Field */}
            <div>
              <label className="block text-xs font-semibold text-[#CBD5E1] uppercase tracking-wider mb-1.5" htmlFor="phone">
                Phone Number (Optional)
              </label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-[#CBD5E1]/60">
                  <Phone className="h-4.5 w-4.5" />
                </div>
                <input
                  id="phone"
                  type="tel"
                  disabled={otpSent}
                  value={phone}
                  onChange={(e) => setPhone(e.target.value)}
                  className="block w-full pl-10 pr-4 py-2.5 bg-[#0F172A]/60 border border-[#334155] rounded-xl text-white placeholder-[#CBD5E1]/40 focus:ring-2 focus:ring-[#2563EB] focus:border-transparent outline-none transition-all duration-200 text-sm disabled:opacity-50"
                  placeholder="+1 (555) 000-0000"
                />
              </div>
            </div>

            {/* Password Field */}
            <div>
              <div className="flex justify-between items-center mb-1.5">
                <label className="block text-xs font-semibold text-[#CBD5E1] uppercase tracking-wider" htmlFor="password">
                  Password *
                </label>
                {!otpSent && (
                  <button
                    type="button"
                    onClick={generateSuggestedPassword}
                    className="text-[11px] text-[#06B6D4] hover:text-[#22D3EE] hover:underline flex items-center gap-1 font-semibold transition-all duration-200 bg-transparent border-0 cursor-pointer text-right"
                  >
                    <Sparkles className="h-3 w-3" />
                    Suggest Password
                  </button>
                )}
              </div>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-[#CBD5E1]/60">
                  <Lock className="h-4.5 w-4.5" />
                </div>
                <input
                  id="password"
                  type={showPassword ? "text" : "password"}
                  required
                  disabled={otpSent}
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  className="block w-full pl-10 pr-10 py-2.5 bg-[#0F172A]/60 border border-[#334155] rounded-xl text-white placeholder-[#CBD5E1]/40 focus:ring-2 focus:ring-[#2563EB] focus:border-transparent outline-none transition-all duration-200 text-sm disabled:opacity-50"
                  placeholder="••••••••"
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute inset-y-0 right-0 pr-3 flex items-center text-[#CBD5E1]/60 hover:text-white bg-transparent border-0 cursor-pointer"
                >
                  {showPassword ? <EyeOff className="h-4.5 w-4.5" /> : <Eye className="h-4.5 w-4.5" />}
                </button>
              </div>
              {!otpSent && (
                <p className="text-[10px] text-[#CBD5E1]/50 mt-1 leading-normal">
                  Min 8 chars, must contain 1 uppercase, 1 lowercase, 1 number, and 1 special char.
                </p>
              )}
            </div>

            {/* Confirm Password Field */}
            <div>
              <label className="block text-xs font-semibold text-[#CBD5E1] uppercase tracking-wider mb-1.5" htmlFor="confirmPassword">
                Confirm Password *
              </label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-[#CBD5E1]/60">
                  <Lock className="h-4.5 w-4.5" />
                </div>
                <input
                  id="confirmPassword"
                  type={showPassword ? "text" : "password"}
                  required
                  disabled={otpSent}
                  value={confirmPassword}
                  onChange={(e) => setConfirmPassword(e.target.value)}
                  className="block w-full pl-10 pr-10 py-2.5 bg-[#0F172A]/60 border border-[#334155] rounded-xl text-white placeholder-[#CBD5E1]/40 focus:ring-2 focus:ring-[#2563EB] focus:border-transparent outline-none transition-all duration-200 text-sm disabled:opacity-50"
                  placeholder="••••••••"
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute inset-y-0 right-0 pr-3 flex items-center text-[#CBD5E1]/60 hover:text-white bg-transparent border-0 cursor-pointer"
                >
                  {showPassword ? <EyeOff className="h-4.5 w-4.5" /> : <Eye className="h-4.5 w-4.5" />}
                </button>
              </div>
            </div>

            {/* OTP Code Verification Input */}
            {otpSent && (
              <motion.div
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: "auto" }}
                className="pt-2 border-t border-[#334155]/40"
              >
                <label className="block text-xs font-bold text-[#A78BFA] uppercase tracking-wider mb-1.5" htmlFor="otp">
                  Enter 6-Digit Verification Code *
                </label>
                <div className="relative">
                  <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-[#A78BFA]/70">
                    <KeyRound className="h-4.5 w-4.5" />
                  </div>
                  <input
                    id="otp"
                    type="text"
                    required
                    value={otp}
                    onChange={(e) => setOtp(e.target.value)}
                    className="block w-full pl-10 pr-4 py-2.5 bg-[#0F172A]/80 border border-[#7C3AED]/50 rounded-xl text-white placeholder-[#CBD5E1]/30 focus:ring-2 focus:ring-[#7C3AED] focus:border-transparent outline-none transition-all duration-200 text-sm font-semibold tracking-widest text-center"
                    placeholder="000000"
                    maxLength={6}
                  />
                </div>
                <div className="flex justify-between items-center mt-2 text-[10px]">
                  <span className="text-[#CBD5E1]/50">Code expires in 50 seconds</span>
                  {cooldown > 0 ? (
                    <span className="text-[#CBD5E1]/60">Resend in {cooldown}s</span>
                  ) : (
                    <button
                      type="button"
                      onClick={handleSendOtp}
                      className="text-[#06B6D4] hover:underline font-semibold"
                    >
                      Resend Verification Code
                    </button>
                  )}
                </div>
              </motion.div>
            )}

            {/* Action Buttons */}
            {!otpSent ? (
              <motion.button
                whileHover={{ scale: 1.01 }}
                whileTap={{ scale: 0.99 }}
                type="button"
                onClick={handleSendOtp}
                disabled={otpSending || !email || !name || !password || !confirmPassword}
                className="w-full flex items-center justify-center gap-2 py-3 px-4 rounded-xl text-sm font-semibold text-white bg-gradient-to-r from-[#2563EB] to-[#7C3AED] hover:from-[#3B82F6] hover:to-[#8B5CF6] shadow-lg shadow-blue-500/25 transition-all duration-300 disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer mt-4"
              >
                {otpSending ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin" />
                    Sending Code...
                  </>
                ) : (
                  <>
                    Send Verification Code
                    <ArrowRight className="h-4 w-4" />
                  </>
                )}
              </motion.button>
            ) : (
              <div className="flex gap-3 mt-4">
                <button
                  type="button"
                  onClick={() => setOtpSent(false)}
                  className="px-4 py-3 border border-[#334155] rounded-xl text-xs text-[#CBD5E1] hover:text-white transition-all"
                >
                  Edit Profile
                </button>
                <motion.button
                  whileHover={{ scale: 1.01 }}
                  whileTap={{ scale: 0.99 }}
                  type="submit"
                  disabled={isSubmitting || !otp}
                  className="flex-grow flex items-center justify-center gap-2 py-3 px-4 rounded-xl text-sm font-semibold text-white bg-gradient-to-r from-emerald-500 to-teal-600 hover:from-emerald-400 hover:to-teal-500 shadow-lg shadow-emerald-500/20 disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer"
                >
                  {isSubmitting ? (
                    <>
                      <Loader2 className="h-4 w-4 animate-spin" />
                      Verifying...
                    </>
                  ) : (
                    <>
                      Verify & Register
                      <ArrowRight className="h-4 w-4" />
                    </>
                  )}
                </motion.button>
              </div>
            )}
          </form>

          {/* OR Divider */}
          <div className="relative my-5">
            <div className="absolute inset-0 flex items-center">
              <div className="w-full border-t border-[#334155]/40" />
            </div>
            <div className="relative flex justify-center text-[10px] uppercase">
              <span className="bg-[#182235] px-2.5 text-[#CBD5E1]/50 font-semibold tracking-wider">
                Or Sign Up With
              </span>
            </div>
          </div>

          {/* Social Buttons */}
          <div className="grid grid-cols-2 gap-2.5">
            <button
              type="button"
              onClick={() => handleSocialRegister("Google")}
              disabled={isSubmitting}
              className="flex items-center justify-center gap-1.5 py-2 px-3 bg-[#0F172A]/70 hover:bg-[#1E293B] border border-[#334155] rounded-xl text-xs font-semibold text-white transition-all cursor-pointer disabled:opacity-50"
            >
              <svg className="h-3.5 w-3.5" viewBox="0 0 24 24" fill="currentColor">
                <path d="M12.24 10.285V14.4h6.887c-.648 2.41-2.519 4.114-5.187 4.114-3.478 0-6.3-2.822-6.3-6.3 0-3.478 2.822-6.3 6.3-6.3 1.543 0 2.94.557 4.028 1.488l3.125-3.124C18.99 2.215 15.86 1 12.24 1 6.033 1 1 6.033 1 12.24s5.033 11.24 11.24 11.24c5.89 0 10.967-4.113 10.967-11.24 0-.768-.085-1.464-.23-1.955H12.24z" fill="#EA4335"/>
              </svg>
              Google
            </button>
            <button
              type="button"
              onClick={() => handleSocialRegister("Microsoft")}
              disabled={isSubmitting}
              className="flex items-center justify-center gap-1.5 py-2 px-3 bg-[#0F172A]/70 hover:bg-[#1E293B] border border-[#334155] rounded-xl text-xs font-semibold text-white transition-all cursor-pointer disabled:opacity-50"
            >
              <svg className="h-3.5 w-3.5" viewBox="0 0 23 23" fill="currentColor">
                <path d="M0 0h11v11H0z" fill="#F25022"/>
                <path d="M12 0h11v11H12z" fill="#7FBA00"/>
                <path d="M0 12h11v11H0z" fill="#00A4EF"/>
                <path d="M12 12h11v11H12z" fill="#FFB900"/>
              </svg>
              Microsoft
            </button>
            <button
              type="button"
              onClick={() => handleSocialRegister("GitHub")}
              disabled={isSubmitting}
              className="flex items-center justify-center gap-1.5 py-2 px-3 bg-[#0F172A]/70 hover:bg-[#1E293B] border border-[#334155] rounded-xl text-xs font-semibold text-white transition-all cursor-pointer disabled:opacity-50"
            >
              <Github className="h-3.5 w-3.5 text-[#CBD5E1]" />
              GitHub
            </button>
            <button
              type="button"
              onClick={() => handleSocialRegister("Mobile")}
              disabled={isSubmitting}
              className="flex items-center justify-center gap-1.5 py-2 px-3 bg-[#0F172A]/70 hover:bg-[#1E293B] border border-[#334155] rounded-xl text-xs font-semibold text-white transition-all cursor-pointer disabled:opacity-50"
            >
              <Phone className="h-3.5 w-3.5 text-[#CBD5E1]" />
              Mobile OTP
            </button>
          </div>

          {/* Form Footer */}
          <div className="mt-5 text-center text-xs">
            <span className="text-[#CBD5E1]/60">Already have an account? </span>
            <Link
              to="/login"
              className="font-semibold text-[#06B6D4] hover:text-[#22D3EE] hover:underline transition-colors duration-200"
            >
              Sign In
            </Link>
          </div>
        </div>
      </motion.div>
    </div>
  );
};

export default Register;
